-- Module 16 — AI Knowledge Platform (KnowledgeDocument/KnowledgeChunk) +
-- Module 04 — Recommendation Engine feedback signal (RecommendationFeedback).
--
-- HYGIENE NOTE (2026-07-23): this migration was originally generated by a
-- concurrent `prisma migrate dev` run that also picked up in-flight schema
-- changes from sibling modules (Escalations, Pricing) that had not yet been
-- committed as their own migrations at the time. That made this file
-- `CREATE TYPE`/`CREATE TABLE` things it does not own (`EscalationStatus`,
-- `EscalationTicket`, `MarkupRule`, `PromoCode`, `PricingConfig`), which
-- collides with `20260723065730_escalations` and `20260723120100_pricing_engine`
-- on a fresh `prisma migrate deploy` shadow-DB replay ("relation already
-- exists" / "type already exists"). This file was trimmed on 2026-07-23 to
-- contain ONLY what Module 16 and Module 04 actually own. See
-- docs/MIGRATION_NOTES.md for the full history. The already-applied
-- production/dev DB is unaffected — the tables below already exist there via
-- this same migration name; only the recorded SQL text changed.

-- CreateEnum
CREATE TYPE "KnowledgeCategory" AS ENUM ('SOP', 'AIRLINE_POLICY', 'SUPPLIER_CONTRACT', 'VISA', 'CORPORATE', 'TRAVEL_POLICY', 'OTHER');

-- CreateEnum
CREATE TYPE "RecommendationSignal" AS ENUM ('ACCEPT', 'REJECT', 'IGNORE');

-- CreateTable
CREATE TABLE "KnowledgeDocument" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "category" "KnowledgeCategory" NOT NULL,
    "source" TEXT,
    "version" INTEGER NOT NULL DEFAULT 1,
    "lastVerifiedAt" TIMESTAMP(3),
    "content" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "KnowledgeDocument_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "KnowledgeChunk" (
    "id" TEXT NOT NULL,
    "documentId" TEXT NOT NULL,
    "ordinal" INTEGER NOT NULL,
    "content" TEXT NOT NULL,
    "tags" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "KnowledgeChunk_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecommendationFeedback" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "offerId" TEXT NOT NULL,
    "conversationId" TEXT,
    "signal" "RecommendationSignal" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RecommendationFeedback_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "KnowledgeDocument_category_idx" ON "KnowledgeDocument"("category");

-- CreateIndex
CREATE INDEX "KnowledgeDocument_isActive_idx" ON "KnowledgeDocument"("isActive");

-- CreateIndex
CREATE INDEX "KnowledgeChunk_documentId_idx" ON "KnowledgeChunk"("documentId");

-- CreateIndex
CREATE INDEX "RecommendationFeedback_userId_idx" ON "RecommendationFeedback"("userId");

-- CreateIndex
CREATE INDEX "RecommendationFeedback_offerId_idx" ON "RecommendationFeedback"("offerId");

-- CreateIndex
CREATE INDEX "RecommendationFeedback_conversationId_idx" ON "RecommendationFeedback"("conversationId");

-- AddForeignKey
ALTER TABLE "KnowledgeChunk" ADD CONSTRAINT "KnowledgeChunk_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "KnowledgeDocument"("id") ON DELETE CASCADE ON UPDATE CASCADE;
