"use client";

import { useState } from "react";
import { Button, Input, QrCode, Spinner } from "@/components/ui";
import { TravellerSection, TravellerChip } from "@/app/components/traveller";
import { useAuthStore } from "@/store/auth.store";
import {
  useTwoFactorSetupMutation,
  useTwoFactorConfirmMutation,
  useTwoFactorDisableMutation,
  type TwoFactorSetupResponse,
} from "@/lib/api/auth.api";

type FlowMode = "idle" | "enrolling" | "backup_codes" | "disabling";

export function TwoFactorSection() {
  const user = useAuthStore((s) => s.user);
  const isEnabled = Boolean(user?.twoFactorEnabled);

  const [mode, setMode] = useState<FlowMode>("idle");
  const [setupData, setSetupData] = useState<TwoFactorSetupResponse | null>(null);
  const [confirmCode, setConfirmCode] = useState("");
  const [disablePassword, setDisablePassword] = useState("");
  const [disableCode, setDisableCode] = useState("");
  const [copiedSecret, setCopiedSecret] = useState(false);
  const [copiedCodes, setCopiedCodes] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [statusMessage, setStatusMessage] = useState<string | null>(null);

  const [setup2fa, { isLoading: isStartingSetup }] = useTwoFactorSetupMutation();
  const [confirm2fa, { isLoading: isConfirming }] = useTwoFactorConfirmMutation();
  const [disable2fa, { isLoading: isDisabling }] = useTwoFactorDisableMutation();

  async function handleStartSetup() {
    setErrorMessage(null);
    setStatusMessage(null);
    setConfirmCode("");
    try {
      const data = await setup2fa().unwrap();
      setSetupData(data);
      setMode("enrolling");
    } catch (err: any) {
      setErrorMessage(
        err?.data?.error || err?.data?.message || "Failed to initialize 2FA setup. Please try again."
      );
    }
  }

  async function handleConfirmSetup(e: React.FormEvent) {
    e.preventDefault();
    if (!confirmCode.trim()) return;
    setErrorMessage(null);
    try {
      await confirm2fa({ code: confirmCode.trim() }).unwrap();
      setStatusMessage("Two-factor authentication successfully enabled!");
      setMode("backup_codes");
    } catch (err: any) {
      setErrorMessage(
        err?.data?.error || err?.data?.message || "Invalid verification code. Please check your authenticator app and try again."
      );
    }
  }

  function handleDismissBackupCodes() {
    // Zero out sensitive one-time setup data from memory
    setSetupData(null);
    setConfirmCode("");
    setMode("idle");
  }

  async function handleDisable2fa(e: React.FormEvent) {
    e.preventDefault();
    setErrorMessage(null);
    try {
      await disable2fa({
        password: disablePassword.trim() || undefined,
        code: disableCode.trim() || undefined,
      }).unwrap();
      setStatusMessage("Two-factor authentication has been disabled.");
      setDisablePassword("");
      setDisableCode("");
      setMode("idle");
    } catch (err: any) {
      setErrorMessage(
        err?.data?.error || err?.data?.message || "Could not disable 2FA. Please verify your password or authenticator code."
      );
    }
  }

  function handleCopySecret() {
    if (!setupData?.secret) return;
    navigator.clipboard.writeText(setupData.secret);
    setCopiedSecret(true);
    setTimeout(() => setCopiedSecret(false), 2000);
  }

  function handleCopyBackupCodes() {
    if (!setupData?.backupCodes?.length) return;
    navigator.clipboard.writeText(setupData.backupCodes.join("\n"));
    setCopiedCodes(true);
    setTimeout(() => setCopiedCodes(false), 2500);
  }

  const qrUri = setupData?.otpauthUrl || setupData?.otpauthUri || "";

  return (
    <TravellerSection
      title="Two-Factor Authentication"
      note="Add an extra layer of defense. In addition to your password, a 6-digit TOTP code generated by your mobile authenticator app will be required to sign in."
    >
      {/* Status Banner */}
      <div className="rounded-2xl border border-slate-200/90 bg-white p-5 shadow-xs transition-all">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex items-start sm:items-center gap-3.5">
            <div
              className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl font-bold text-lg ${
                isEnabled
                  ? "bg-emerald-500/10 text-emerald-600 dark:bg-emerald-500/20 dark:text-emerald-400"
                  : "bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-400"
              }`}
            >
              {isEnabled ? "🛡️" : "🔒"}
            </div>
            <div>
              <div className="flex items-center gap-2">
                <span className="font-semibold text-slate-900 dark:text-white">
                  {isEnabled ? "Two-Factor Authentication is Active" : "Two-Factor Authentication is Disabled"}
                </span>
                <TravellerChip tone={isEnabled ? "default" : "muted"}>
                  {isEnabled ? "Protected" : "Optional"}
                </TravellerChip>
              </div>
              <p className="mt-0.5 text-xs text-slate-500 dark:text-slate-400">
                {isEnabled
                  ? "Your account requires an authenticator TOTP code or single-use recovery code on sign-in."
                  : "Protect your personal traveler information and bookings against unauthorized access."}
              </p>
            </div>
          </div>

          {mode === "idle" && (
            <div className="shrink-0 pt-1 sm:pt-0">
              {isEnabled ? (
                <Button
                  type="button"
                  variant="secondary"
                  size="sm"
                  onClick={() => {
                    setErrorMessage(null);
                    setStatusMessage(null);
                    setMode("disabling");
                  }}
                  className="text-rose-600 hover:text-rose-700 hover:border-rose-300"
                >
                  Disable 2FA
                </Button>
              ) : (
                <Button
                  type="button"
                  size="sm"
                  onClick={handleStartSetup}
                  disabled={isStartingSetup}
                >
                  {isStartingSetup ? (
                    <>
                      <Spinner size="sm" label={null} />
                      Initializing…
                    </>
                  ) : (
                    "Enable Two-Factor"
                  )}
                </Button>
              )}
            </div>
          )}
        </div>

        {/* Global Feedback Notifications */}
        {statusMessage && mode === "idle" && (
          <div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50/70 p-3 text-xs font-medium text-emerald-800">
            ✓ {statusMessage}
          </div>
        )}

        {errorMessage && mode === "idle" && (
          <div className="mt-4 rounded-xl border border-rose-200 bg-rose-50/70 p-3 text-xs font-medium text-rose-800" role="alert">
            ⚠ {errorMessage}
          </div>
        )}
      </div>

      {/* FLOW 1: ENROLLMENT WIZARD */}
      {mode === "enrolling" && setupData && (
        <div className="rounded-2xl border border-cyan-200/80 bg-cyan-50/20 p-5 sm:p-6 shadow-xs animate-in fade-in duration-200">
          <div className="flex items-center justify-between border-b border-cyan-100 pb-3 mb-5">
            <div>
              <h3 className="text-sm font-bold text-slate-900 dark:text-white flex items-center gap-2">
                <span className="flex h-5 w-5 items-center justify-center rounded-full bg-cyan-600 text-[11px] text-white">1</span>
                Connect Authenticator App
              </h3>
              <p className="text-xs text-slate-500 mt-0.5">
                Compatible with Google Authenticator, 1Password, Microsoft Authenticator, or Bitwarden.
              </p>
            </div>
            <Button
              type="button"
              variant="ghost"
              size="sm"
              onClick={() => {
                setSetupData(null);
                setMode("idle");
              }}
            >
              Cancel
            </Button>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-[auto_1fr] gap-6 items-start">
            {/* Left: QR Code */}
            <div className="flex flex-col items-center justify-center rounded-2xl border border-slate-200 bg-white p-4 text-center">
              <QrCode value={qrUri} size={168} alt="FlightOne 2FA QR Code" />
              <span className="mt-2 text-[11px] font-medium text-slate-400">
                Scan with your phone camera or app
              </span>
            </div>

            {/* Right: Manual Setup & Code Confirmation Form */}
            <div className="space-y-4">
              <div>
                <label className="text-xs font-semibold text-slate-700 dark:text-slate-300">
                  Can&apos;t scan? Enter this secret manually:
                </label>
                <div className="mt-1 flex items-center gap-2">
                  <code className="block flex-1 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs sm:text-sm font-mono tracking-wider font-semibold text-slate-800 select-all">
                    {setupData.secret}
                  </code>
                  <Button
                    type="button"
                    variant="secondary"
                    size="sm"
                    onClick={handleCopySecret}
                    className="shrink-0 text-xs"
                  >
                    {copiedSecret ? "✓ Copied" : "Copy"}
                  </Button>
                </div>
              </div>

              <form onSubmit={handleConfirmSetup} className="space-y-4 pt-2">
                <div>
                  <label htmlFor="totp-confirm-input" className="block text-xs font-semibold text-slate-700 dark:text-slate-300">
                    Step 2: Enter the 6-digit code shown in your app
                  </label>
                  <div className="mt-1 flex max-w-xs items-center gap-2">
                    <Input
                      id="totp-confirm-input"
                      type="text"
                      inputMode="numeric"
                      pattern="[0-9]*"
                      maxLength={6}
                      autoFocus
                      required
                      placeholder="000000"
                      value={confirmCode}
                      onChange={(e) => setConfirmCode(e.target.value.replace(/\D/g, "").slice(0, 6))}
                      className="font-mono text-center text-lg tracking-widest font-bold"
                      disabled={isConfirming}
                    />
                  </div>
                </div>

                {errorMessage && (
                  <p className="text-xs font-medium text-rose-600" role="alert">
                    ⚠ {errorMessage}
                  </p>
                )}

                <div className="flex items-center gap-3 pt-1">
                  <Button
                    type="submit"
                    size="sm"
                    disabled={confirmCode.length < 6 || isConfirming}
                  >
                    {isConfirming ? (
                      <>
                        <Spinner size="sm" label={null} />
                        Confirming…
                      </>
                    ) : (
                      "Confirm & Activate 2FA"
                    )}
                  </Button>
                  <Button
                    type="button"
                    variant="ghost"
                    size="sm"
                    onClick={() => {
                      setSetupData(null);
                      setMode("idle");
                    }}
                  >
                    Cancel
                  </Button>
                </div>
              </form>
            </div>
          </div>
        </div>
      )}

      {/* FLOW 2: ONE-TIME BACKUP RECOVERY CODES DISPLAY */}
      {mode === "backup_codes" && setupData && (
        <div className="rounded-2xl border border-amber-300 bg-amber-50/40 p-5 sm:p-6 shadow-xs animate-in zoom-in-95 duration-200">
          <div className="flex items-start gap-3.5 mb-4">
            <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-amber-500/10 text-amber-700 text-xl font-bold">
              🔑
            </span>
            <div>
              <h3 className="text-base font-bold text-slate-900 dark:text-white">
                Save your emergency backup codes
              </h3>
              <p className="mt-0.5 text-xs text-amber-900/80">
                If you lose access to your authenticator app, these single-use recovery codes are the
                only way to sign in. Store them in a secure password manager.
                <strong className="block mt-1 text-amber-950 font-semibold">
                  These codes will never be displayed again after you leave this page.
                </strong>
              </p>
            </div>
          </div>

          <div className="mt-4 rounded-xl border border-slate-200 bg-white p-4">
            <div className="grid grid-cols-2 sm:grid-cols-5 gap-2.5 font-mono text-xs sm:text-sm font-semibold tracking-wider text-slate-800 text-center">
              {setupData.backupCodes.map((code, idx) => (
                <div
                  key={idx}
                  className="rounded-lg bg-slate-50 border border-slate-100 py-1.5 px-2 select-all hover:bg-slate-100 transition-colors"
                >
                  {code}
                </div>
              ))}
            </div>

            <div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 pt-3">
              <Button
                type="button"
                variant="secondary"
                size="sm"
                onClick={handleCopyBackupCodes}
                className="text-xs"
              >
                {copiedCodes ? "✓ Copied 10 Codes" : "📋 Copy All Codes"}
              </Button>
              <span className="text-[11px] text-slate-400">
                10 single-use codes · 8 characters each
              </span>
            </div>
          </div>

          <div className="mt-6 flex items-center justify-end">
            <Button
              type="button"
              onClick={handleDismissBackupCodes}
              className="bg-slate-900 text-white hover:bg-slate-800"
            >
              I have safely stored my backup codes
            </Button>
          </div>
        </div>
      )}

      {/* FLOW 3: DISABLE 2FA CONFIRMATION */}
      {mode === "disabling" && (
        <div className="rounded-2xl border border-rose-200 bg-rose-50/30 p-5 sm:p-6 shadow-xs animate-in fade-in duration-200">
          <div className="flex items-start gap-3 mb-4">
            <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-rose-500/10 text-rose-600 text-lg">
              ⚠
            </span>
            <div>
              <h3 className="text-sm font-bold text-slate-900">
                Disable Two-Factor Authentication
              </h3>
              <p className="mt-0.5 text-xs text-rose-800/80">
                Disabling 2FA reduces your account security. Please verify your identity by entering
                your account password or a 6-digit TOTP code from your authenticator app.
              </p>
            </div>
          </div>

          <form onSubmit={handleDisable2fa} className="space-y-4 max-w-md">
            <div>
              <label className="block text-xs font-semibold text-slate-700">
                Account Password
              </label>
              <Input
                type="password"
                placeholder="••••••••"
                value={disablePassword}
                onChange={(e) => setDisablePassword(e.target.value)}
                disabled={isDisabling}
                className="mt-1"
              />
            </div>

            <div className="text-center text-[11px] font-semibold text-slate-400 uppercase tracking-wider">
              — OR —
            </div>

            <div>
              <label className="block text-xs font-semibold text-slate-700">
                Current 6-Digit Authenticator Code
              </label>
              <Input
                type="text"
                inputMode="numeric"
                pattern="[0-9]*"
                maxLength={6}
                placeholder="000000"
                value={disableCode}
                onChange={(e) => setDisableCode(e.target.value.replace(/\D/g, "").slice(0, 6))}
                disabled={isDisabling}
                className="mt-1 font-mono tracking-widest"
              />
            </div>

            {errorMessage && (
              <p className="text-xs font-medium text-rose-600" role="alert">
                ⚠ {errorMessage}
              </p>
            )}

            <div className="flex items-center gap-3 pt-2">
              <Button
                type="submit"
                variant="secondary"
                size="sm"
                disabled={(!disablePassword.trim() && disableCode.length < 6) || isDisabling}
                className="text-rose-600 border-rose-300 hover:bg-rose-50"
              >
                {isDisabling ? (
                  <>
                    <Spinner size="sm" label={null} />
                    Disabling…
                  </>
                ) : (
                  "Confirm & Disable 2FA"
                )}
              </Button>
              <Button
                type="button"
                variant="ghost"
                size="sm"
                onClick={() => {
                  setDisablePassword("");
                  setDisableCode("");
                  setErrorMessage(null);
                  setMode("idle");
                }}
              >
                Cancel
              </Button>
            </div>
          </form>
        </div>
      )}
    </TravellerSection>
  );
}
