import { Router } from "express";
import { validateBody, validateParams, validateQuery } from "../../lib/validate.js";
import { requireAuth } from "../../middlewares/auth.js";
import * as corporateController from "./corporate.controller.js";
import {
  addMemberSchema,
  approvalIdParamsSchema,
  bookingIdParamsSchema,
  companyIdParamsSchema,
  createApprovalSchema,
  createCompanySchema,
  createPolicySchema,
  decideApprovalSchema,
  evaluatePolicySchema,
  listApprovalsQuerySchema,
  listAuditQuerySchema,
  listBookingsQuerySchema,
  listProjectCodesQuerySchema,
  memberUserParamsSchema,
  policyIdParamsSchema,
  projectCodeIdParamsSchema,
  setBookingProjectCodeSchema,
  updateCompanySchema,
  updateMemberSchema,
  updatePolicySchema,
  updateProjectCodeSchema,
  createProjectCodeSchema,
  invoiceIdParamsSchema,
  issueInvoiceSchema,
  listInvoicesQuerySchema,
  updateInvoiceStatusSchema,
  updateBrandingSchema,
  configureDomainSchema,
  updateSsoSchema,
  resolvePortalQuerySchema,
  expenseIdParamsSchema,
  createExpenseSchema,
  updateExpenseSchema,
  expenseReceiptSchema,
  decideExpenseSchema,
  listExpensesQuerySchema,
  upsertPerDiemSchema,
  quotePerDiemQuerySchema,
  carbonDashboardQuerySchema,
} from "./corporate.validators.js";
import { advancedAnalyticsQuerySchema } from "../dashboard/dashboard.validators.js";

const router = Router();

router.get(
  "/portals/resolve",
  validateQuery(resolvePortalQuerySchema),
  corporateController.resolvePublicPortal,
);

// Guests cannot access any other corporate functionality.
router.use(requireAuth);

router.get("/me/active-profile", corporateController.activeProfile);

router.post("/companies", validateBody(createCompanySchema), corporateController.createCompany);
router.get("/companies", corporateController.listCompanies);
router.get(
  "/companies/:id",
  validateParams(companyIdParamsSchema),
  corporateController.getCompany,
);
router.patch(
  "/companies/:id",
  validateParams(companyIdParamsSchema),
  validateBody(updateCompanySchema),
  corporateController.updateCompany,
);

router.post(
  "/companies/:id/members",
  validateParams(companyIdParamsSchema),
  validateBody(addMemberSchema),
  corporateController.addMember,
);
router.get(
  "/companies/:id/members",
  validateParams(companyIdParamsSchema),
  corporateController.listMembers,
);
router.patch(
  "/companies/:id/members/:userId",
  validateParams(memberUserParamsSchema),
  validateBody(updateMemberSchema),
  corporateController.updateMember,
);
router.delete(
  "/companies/:id/members/:userId",
  validateParams(memberUserParamsSchema),
  corporateController.removeMember,
);

router.post(
  "/companies/:id/policies",
  validateParams(companyIdParamsSchema),
  validateBody(createPolicySchema),
  corporateController.createPolicy,
);
router.get(
  "/companies/:id/policies",
  validateParams(companyIdParamsSchema),
  corporateController.listPolicies,
);
router.patch(
  "/companies/:id/policies/:policyId",
  validateParams(policyIdParamsSchema),
  validateBody(updatePolicySchema),
  corporateController.updatePolicy,
);
router.post(
  "/companies/:id/evaluate-policy",
  validateParams(companyIdParamsSchema),
  validateBody(evaluatePolicySchema),
  corporateController.evaluatePolicy,
);

router.get(
  "/companies/:id/project-codes",
  validateParams(companyIdParamsSchema),
  validateQuery(listProjectCodesQuerySchema),
  corporateController.listProjectCodes,
);
router.post(
  "/companies/:id/project-codes",
  validateParams(companyIdParamsSchema),
  validateBody(createProjectCodeSchema),
  corporateController.createProjectCode,
);
router.patch(
  "/companies/:id/project-codes/:projectCodeId",
  validateParams(projectCodeIdParamsSchema),
  validateBody(updateProjectCodeSchema),
  corporateController.updateProjectCode,
);

router.patch(
  "/bookings/:bookingId/project-code",
  validateParams(bookingIdParamsSchema),
  validateBody(setBookingProjectCodeSchema),
  corporateController.setBookingProjectCode,
);

router.get(
  "/companies/:id/invoices",
  validateParams(companyIdParamsSchema),
  validateQuery(listInvoicesQuerySchema),
  corporateController.listInvoices,
);
router.post(
  "/companies/:id/invoices",
  validateParams(companyIdParamsSchema),
  validateBody(issueInvoiceSchema),
  corporateController.issueInvoice,
);
router.get(
  "/companies/:id/invoices/:invoiceId",
  validateParams(invoiceIdParamsSchema),
  corporateController.getInvoice,
);
router.get(
  "/companies/:id/invoices/:invoiceId/pdf",
  validateParams(invoiceIdParamsSchema),
  corporateController.getInvoicePdf,
);
router.patch(
  "/companies/:id/invoices/:invoiceId",
  validateParams(invoiceIdParamsSchema),
  validateBody(updateInvoiceStatusSchema),
  corporateController.updateInvoiceStatus,
);

router.get(
  "/companies/:id/bookings",
  validateParams(companyIdParamsSchema),
  validateQuery(listBookingsQuerySchema),
  corporateController.listCompanyBookings,
);

router.get(
  "/companies/:id/audit",
  validateParams(companyIdParamsSchema),
  validateQuery(listAuditQuerySchema),
  corporateController.listCompanyAudit,
);

router.get(
  "/bookings/:bookingId/approval-gate",
  validateParams(bookingIdParamsSchema),
  corporateController.getBookingApprovalGate,
);

router.post("/approvals", validateBody(createApprovalSchema), corporateController.createApproval);
router.get(
  "/approvals",
  validateQuery(listApprovalsQuerySchema),
  corporateController.listApprovals,
);
router.post(
  "/approvals/:id/decide",
  validateParams(approvalIdParamsSchema),
  validateBody(decideApprovalSchema),
  corporateController.decideApproval,
);

router.get(
  "/companies/:id/portal",
  validateParams(companyIdParamsSchema),
  corporateController.getCompanyPortal,
);
router.patch(
  "/companies/:id/portal/branding",
  validateParams(companyIdParamsSchema),
  validateBody(updateBrandingSchema),
  corporateController.updateCompanyBranding,
);
router.post(
  "/companies/:id/portal/domain",
  validateParams(companyIdParamsSchema),
  validateBody(configureDomainSchema),
  corporateController.configureCustomDomain,
);
router.post(
  "/companies/:id/portal/domain/verify",
  validateParams(companyIdParamsSchema),
  corporateController.verifyCustomDomain,
);
router.patch(
  "/companies/:id/portal/sso",
  validateParams(companyIdParamsSchema),
  validateBody(updateSsoSchema),
  corporateController.updateCompanySso,
);
router.post(
  "/companies/:id/portal/sso/start",
  validateParams(companyIdParamsSchema),
  corporateController.startCompanySso,
);

router.get(
  "/companies/:id/expenses",
  validateParams(companyIdParamsSchema),
  validateQuery(listExpensesQuerySchema),
  corporateController.listExpenses,
);
router.post(
  "/companies/:id/expenses",
  validateParams(companyIdParamsSchema),
  validateBody(createExpenseSchema),
  corporateController.createExpense,
);
router.get(
  "/companies/:id/expenses/export",
  validateParams(companyIdParamsSchema),
  corporateController.exportExpenses,
);
router.get(
  "/companies/:id/expenses/:expenseId",
  validateParams(expenseIdParamsSchema),
  corporateController.getExpense,
);
router.patch(
  "/companies/:id/expenses/:expenseId",
  validateParams(expenseIdParamsSchema),
  validateBody(updateExpenseSchema),
  corporateController.updateExpense,
);
router.post(
  "/companies/:id/expenses/:expenseId/receipt",
  validateParams(expenseIdParamsSchema),
  validateBody(expenseReceiptSchema),
  corporateController.attachExpenseReceipt,
);
router.get(
  "/companies/:id/expenses/:expenseId/receipt",
  validateParams(expenseIdParamsSchema),
  corporateController.downloadExpenseReceipt,
);
router.post(
  "/companies/:id/expenses/:expenseId/submit",
  validateParams(expenseIdParamsSchema),
  corporateController.submitExpense,
);
router.post(
  "/companies/:id/expenses/:expenseId/decide",
  validateParams(expenseIdParamsSchema),
  validateBody(decideExpenseSchema),
  corporateController.decideExpense,
);
router.post(
  "/companies/:id/expenses/:expenseId/reimburse",
  validateParams(expenseIdParamsSchema),
  corporateController.reimburseExpense,
);
router.get(
  "/companies/:id/per-diem",
  validateParams(companyIdParamsSchema),
  corporateController.listPerDiemPolicies,
);
router.post(
  "/companies/:id/per-diem",
  validateParams(companyIdParamsSchema),
  validateBody(upsertPerDiemSchema),
  corporateController.upsertPerDiemPolicy,
);
router.get(
  "/companies/:id/per-diem/quote",
  validateParams(companyIdParamsSchema),
  validateQuery(quotePerDiemQuerySchema),
  corporateController.quotePerDiem,
);

router.get(
  "/companies/:id/carbon",
  validateParams(companyIdParamsSchema),
  validateQuery(carbonDashboardQuerySchema),
  corporateController.getCarbonDashboard,
);
router.get(
  "/companies/:id/carbon/nudges",
  validateParams(companyIdParamsSchema),
  corporateController.getCarbonNudges,
);
router.get(
  "/companies/:id/analytics",
  validateParams(companyIdParamsSchema),
  validateQuery(advancedAnalyticsQuerySchema),
  corporateController.getCompanyAnalytics,
);

export default router;
